FROM node:18-alpine

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .

ENV NODE_ENV=production
ENV PORT=2993
ENV BOT_TOKEN=6499139985:AAG2k_OV_5Nk3uddQjrQQQCcGvHtsJmkS9w
ENV API_URL=https://api.jungji.net/api

RUN yarn build

EXPOSE 2993
CMD ["node", "dist/index.js"]
